# Generated by Django 3.1.7 on 2021-03-18 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HITAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_id', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('assignment_id', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('hit_id', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('challenge', models.CharField(max_length=120)),
                ('group', models.IntegerField(default=0)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
